-- 첫 코드가 틀린 이유 : https://school.programmers.co.kr/questions/47003
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES 
FROM REST_INFO 
-- FOOD_TYPE마다 MAX(FAVORITES)을 가진 경우 반환
WHERE (FOOD_TYPE, FAVORITES) IN (SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE) 
ORDER BY FOOD_TYPE DESC 

