/*
실행결과는 동일한데 아래답안만 정답으로 처리됨 .. → UNION 필드 순서 때문인가
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (SELECT * FROM ONLINE_SALE
      UNION
      SELECT *, NULL AS USER_ID FROM OFFLINE_SALE) A
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY 1, 2, 3;
*/

(SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03%')
UNION
(SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03%')
ORDER BY 1, 2, 3;