/*
1번. 2021년에 가입한 전체 회원들
2번. 상품을 구매한 회원의 비율(=2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수) 소수점 두번째자리에서 반올림
3번. 년, 월 별 결과
4번. 년 오름차순, 월 오름차순 정렬

### 실패
# [시도1]
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT(USER_ID)) AS PUCHASED_USERS, 
TRUNCATE(COUNT(DISTINCT(USER_ID)) / (SELECT COUNT(DISTINCT(USER_ID))
                                     FROM USER_INFO
                                     WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE O JOIN (SELECT *
                         FROM USER_INFO
                         WHERE JOINED LIKE '2021%') I USING (USER_ID)
GROUP BY YEAR, MONTH
ORDER BY 1, 2;

# [시도2]
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH,
      COUNT(DISTINCT(O.USER_ID)) AS PUCHASED_USERS,
      TRUNCATE(COUNT(DISTINCT(O.USER_ID)) / I.TOTAL, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE O, (SELECT USER_ID, COUNT(DISTINCT(USER_ID)) AS TOTAL
                     FROM USER_INFO WHERE JOINED LIKE '2021%') I
GROUP BY YEAR, MONTH
ORDER BY 1, 2;
*/

### 답안
# 1번
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, 
		# 2번
    COUNT(DISTINCT O.USER_ID) PUCHASED_USERS, 
		# 2번 TRUNCATE != ROUND           # 2021년에 가입한 전체 회원 수
    ROUND(COUNT(DISTINCT O.USER_ID)/(SELECT COUNT(DISTINCT USER_ID) 
                                     FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) PUCHASED_RATIO
# 2021년에 가입한 회원 중 상품을 구매한 회원
FROM ONLINE_SALE O INNER JOIN USER_INFO U USING (USER_ID)
WHERE YEAR(JOINED) = 2021
GROUP BY 1,2
ORDER BY 1,2
