/*
[실패]
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, 
			 U.GENDER, COUNT(O.USER_ID) AS USERS
FROM ONLINE_SALE O JOIN (
    SELECT USER_ID, GENDER FROM USER_INFO
    WHERE GENDER IS NOT NULL) U
    ON O.USER_ID = U.USER_ID
GROUP BY YEAR, MONTH, U.GENDER
ORDER BY YEAR, MONTH, U.GENDER;
*/

-- count(user_id) -> count(distinct(user_id))
-- join 된 테이블 결과는 한 회원이 여러 번 구매 이력이 있을 수 있기 때문
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, 
			 U.GENDER, COUNT(DISTINCT(O.USER_ID)) AS USERS
FROM ONLINE_SALE O JOIN (
    SELECT USER_ID, GENDER FROM USER_INFO
    WHERE GENDER IS NOT NULL) U USING (USER_ID)
GROUP BY YEAR, MONTH, U.GENDER
ORDER BY YEAR, MONTH, U.GENDER;