-- 22년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역
SELECT APNT_NO, PT_NAME, PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
    JOIN PATIENT USING (PT_NO)
WHERE APNT_YMD LIKE '2022-04-13%' 
AND A.MCDP_CD = 'CS'
AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;