-- 1차
SELECT I.FLAVOR
FROM FIRST_HALF F, ICECREAM_INFO I
WHERE F.TOTAL_ORDER > 3000 AND I.INGREDIENT_TYPE = 'fruit_based' AND F.FLAVOR = I.FLAVOR
ORDER BY F.TOTAL_ORDER DESC;

-- 2차
SELECT F.FLAVOR
FROM FIRST_HALF F JOIN ICECREAM_INFO I
ON F.FLAVOR = I.FLAVOR
WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;