/*
-- 1차 : 책 별로 total sales 먼저 구한 후, 집계
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM (SELECT AUTHOR_ID, CATEGORY, (PRICE*SALES) AS TOTAL_SALES , SALES_DATE
      FROM BOOK_SALES JOIN BOOK USING (BOOK_ID)
      GROUP BY BOOK_ID HAVING SUM(SALES) 
      ORDER BY AUTHOR_ID, CATEGORY DESC) B
      JOIN
      AUTHOR USING (AUTHOR_ID)
WHERE SALES_DATE LIKE '2022-01-%'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;
*/

-- 2차 : 날짜 필터 안쪽에 걸기 + group by - having 기능 헷갈리지 말기
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM (SELECT AUTHOR_ID, CATEGORY, (PRICE*SUM(SALES)) AS TOTAL_SALES , SALES_DATE
      FROM BOOK_SALES JOIN BOOK USING (BOOK_ID)
      WHERE SALES_DATE LIKE '2022-01-%'
      GROUP BY BOOK_ID
      ORDER BY AUTHOR_ID, CATEGORY DESC) B
      JOIN
      AUTHOR USING (AUTHOR_ID)
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;