/*
-- TABLE T, DATE_FORMAT, GROUP BY
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S, BOOK B
WHERE S.BOOK_ID = B.BOOK_ID
    AND DATE_FORMAT(S.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY;
*/

-- JOIN, ON, YEAR, MONTH, GROUP BY
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '01'
GROUP BY CATEGORY
ORDER BY CATEGORY;