-- SUCCESS

SELECT HISTORY_ID, CAR_ID, 
    DATE_FORMAT(START_DATE,'%Y-%m-%d') AS START_DATE, 
    DATE_FORMAT(END_DATE,'%Y-%m-%d') AS END_DATE,
    -- 대여기간 계산 시, DATEDIFF+1을 해주어야 함
    IF(DATEDIFF(END_DATE, START_DATE)+1 < 30, "단기 대여", "장기 대여") AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) = 9
ORDER BY HISTORY_ID DESC;