/*
1번. 자동차 종류가 '트럭'인 자동차 
2번. 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하기
3번. 대여 금액 내림차순, 대여 기록 ID 내림차순 정렬

SELECT HISTORY_ID, TRUNCATE(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1) * (100-DISCOUNT_RATE)/100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
JOIN CAR_RENTAL_COMPANY_CAR R USING (CAR_ID)
JOIN (SELECT DISCOUNT_RATE, DURATION_TYPE 
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
      WHERE CAR_TYPE = '트럭') D
WHERE CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY 1 DESC, 2 DESC;
*/

SELECT HISTORY_ID, 
# 2번, 1번
ROUND(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1) * (100 - (
    CASE
        WHEN (DATEDIFF(END_DATE, START_DATE)+1) >= 90
        THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
              WHERE DURATION_TYPE = '90일 이상' AND CAR_TYPE = '트럭')
        WHEN (DATEDIFF(END_DATE, START_DATE)+1) >= 30
        THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
              WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE = '트럭')
        WHEN (DATEDIFF(END_DATE, START_DATE)+1) >= 7
        THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
              WHERE DURATION_TYPE = '7일 이상' AND CAR_TYPE = '트럭')
        ELSE 0
    END
)) * 0.01) FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY JOIN CAR_RENTAL_COMPANY_CAR USING (CAR_ID)
# 1번
WHERE CAR_TYPE = '트럭'
# 3번
ORDER BY 2 DESC, 1 DESC;