/*
-- 1차 : 
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATEDIFF(END_DATE, START_DATE) >= 7
GROUP BY CAR_ID
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

-- 2차 : DURATION col 생성하여 쿼리문 작성
SELECT C.CAR_ID, ROUND(AVG(D.DURATION), 1) AS AVERAGE_DURATION
FROM (SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE) AS DURATION
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) D 
     JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY C
     ON D.CAR_ID = C.CAR_ID
WHERE D.DURATION >= 7
GROUP BY CAR_ID
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;
*/

-- 3차 : 문제 제대로 안 읽음 + 대여기간에 대한 정의 제대로
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC