/*
-- 1차 : GROUP BY로 묶으면 가장 상단에 있는 데이터들을 임의로 가져옴
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY HAVING MAX(PRICE)
ORDER BY PRICE DESC;
*/
-- 2차 : 이전 코드 참고
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
    AND PRICE IN (SELECT MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY)
ORDER BY PRICE DESC;