/*
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O JOIN (SELECT * FROM ANIMAL_INS WHERE SEX_UPON_INTAKE LIKE 'Intact%') I
ON O.ANIMAL_ID = I.ANIMAL_ID 
WHERE (O.SEX_UPON_OUTCOME LIKE 'Neutered%' OR O.SEX_UPON_OUTCOME LIKE 'Spayed%')
ORDER BY O.ANIMAL_ID;
*/
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS I, ANIMAL_OUTS O
WHERE I.ANIMAL_ID = O.ANIMAL_ID 
    AND (O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR O.SEX_UPON_OUTCOME LIKE 'Neutered%')
    AND I.SEX_UPON_INTAKE LIKE 'Intact%'
ORDER BY O.ANIMAL_ID;