WITH RECURSIVE H AS (
    SELECT 0 AS HOUR UNION ALL SELECT HOUR + 1 
    FROM H
    WHERE HOUR < 23)

SELECT H.HOUR AS HOUR, COUNT(ANIMAL_ID) AS 'COUNT' 
FROM ANIMAL_OUTS RIGHT JOIN H
ON HOUR(DATETIME) = H.HOUR
GROUP BY HOUR
ORDER BY HOUR ASC;

